### ISSUE TITLE
Article: Commit naming rules

### ISSUE THREAD

**Issue by prokopsimek** [DXHeroes/knowledge-base-content#102]

**Comment by zeman-j4** [comment]
What this is about: Using a unified standard for naming commit makes it easier for developers to understand changes the commit contains.

You can start your research here: https://www.conventionalcommits.org/en/v1.0.0/
https://chris.beams.io/posts/git-commit/

Contribution guide: https://github.com/DXHeroes/knowledge-base-content/blob/master/CONTRIBUTING.md

**Comment by yogesh-hackx** [comment]
can I pick this up? @prokopsimek

**Comment by prokopsimek** [comment]
@yogesh-hackx Sure! Go for it!

**Comment by DominikMilaniak** [comment]
**Hi again** @yogesh-hackx ! 🙂 

A few days have passed since our last contact, how is it going so far with the article? Is anything not clear enough or do you need help with something? I am in no way pushing you, you can take as much time as you need 🙂  Just wanted to get in touch to make sure everything is ok 👍

**Comment by yogesh-hackx** [comment]
Hello,
& sorry for late reply, actually I got stuck due to some health issues.
I'll try to raise a PR by tommorow. ✌🏻

**Comment by DominikMilaniak** [comment]
Hi again @yogesh-hackx!

Please, do not apologize - there is no time limit, you can take as much time as you need to. I just wanted to reach out to you, if everything is ok 🙂  I am sorry to hear you have some health issues, everybody from DX Heroes wishes you as fast as possible recovery ❤️  Looking forward to your article 🙂

**Comment by prokopsimek** [comment]
Hi there, @yogesh-hackx! I am just informing you that we have released a **new feature** to the [DX Knowledge base](https://developerexperience.io), **the author box**.

You are the author of at least one article in the knowledge base, so I am writing to you about it and offering you the opportunity to **add your bio and links under the article**.

![image](https://user-images.githubusercontent.com/5487217/142176190-7e3393c4-9104-4c12-8fe1-9b09c91b8dc7.png)

As you can see, the author box is located at the bottom of the [Apache Kafka page](https://developerexperience.io/practices/kafka).

**If you want to add information about yourself below the article, you must:** 
1. log in to the DX Knowledge Base 
    a. via Github or, 
    b. link your Github account to your Google account on your profile page (https://developerexperience.io/u/me),
2. and fill out the information about yourself in your profile.

If you associate your Github account, an author box will appear in the article.

Thank you and we look forward to placing your box in the article!
