### ISSUE TITLE
Article: Documentation

### ISSUE THREAD

**Issue by prokopsimek** [DXHeroes/knowledge-base-content#111]

**Comment by zeman-j4** [comment]
What this is about: Treat others as you wanna be treated - thus providing your colleagues, new developers or external developers with good documentation of how software works is very important. Documentation removes frustration from having to find out how something works and increases usability of your product for others.

You can start your research here: https://opensource.com/business/15/5/write-better-docs

Contribution guide: https://github.com/DXHeroes/knowledge-base-content/blob/master/CONTRIBUTING.md

**Comment by wilsantow** [comment]
@zeman-j4  Can I work on this?

**Comment by prokopsimek** [comment]
@wilsantow Go for it! 👏

**Comment by wilsantow** [comment]
@prokopsimek I opened a pull request. Can you go through the article and tell me if there is anything to change or add?

**Comment by prokopsimek** [comment]
Hi there, @wilsantow! I am just informing you that we have released a **new feature** to the [DX Knowledge base](https://developerexperience.io), **the author box**.

You are the author of at least one article in the knowledge base, so I am writing to you about it and offering you the opportunity to **add your bio and links under the article**.

![image](https://user-images.githubusercontent.com/5487217/142176190-7e3393c4-9104-4c12-8fe1-9b09c91b8dc7.png)

As you can see, the author box is located at the bottom of the [Apache Kafka page](https://developerexperience.io/practices/kafka).

**If you want to add information about yourself below the article, you must:** 
1. log in to the DX Knowledge Base 
    a. via Github or, 
    b. link your Github account to your Google account on your profile page (https://developerexperience.io/u/me),
2. and fill out the information about yourself in your profile.

If you associate your Github account, an author box will appear in the article.

Thank you and we look forward to placing your box in the article!
