### ISSUE TITLE
Article: Epic

### ISSUE THREAD

**Issue by prokopsimek** [DXHeroes/knowledge-base-content#112]

**Comment by zeman-j4** [comment]
What this is about: Business requirements, turned into user stories, are often times bigger than what can fit scope of one sprint. These bigger, high level requirements, are called epics and aggregate multiple user stories.

You can start your research here: https://www.atlassian.com/agile/project-management/epics

Contribution guide: https://github.com/DXHeroes/knowledge-base-content/blob/master/CONTRIBUTING.md

**Comment by xaylax** [comment]
Hi! Can I work on this issue?

**Comment by DominikMilaniak** [comment]
Hello @xaylax! 🙂 

I am super excited you chose our projects to contribute to. I see you picked 3 articles you want to work on. That's absolutely awesome, I am just wondering if the load isn't too much. I mean there is no time limit, so if you really want to work on all 3 of them, say a word and I will gladly assign you 🙂 

_Btw. I absolutely love your personal readme and how you work with it_ ❤️

**Comment by xaylax** [comment]
Hey @DominikMilaniak ! I think DXHeroes is an awesome initiative and would love to contribute as much as I can! I would totally be ok with doing the 3 articles, I was just wondering how much detail each article had to go into, as well as each article's length. This would definitely help me decide whether I should just stick to one article, or perhaps do all 3 👍

Thanks so much for the comment re. my readme 😁

**Comment by sks147** [comment]
Hi @DominikMilaniak @prokopsimek can I pick up this issue?

**Comment by xaylax** [comment]
I'm busy so I won't be able to commit anymore, so if it's alright with the organizers, go ahead ^^
