### ISSUE TITLE
Article: Extremely programming (XP)

### ISSUE THREAD

**Issue by prokopsimek** [DXHeroes/knowledge-base-content#113]

**Comment by zeman-j4** [comment]
What this is about: Extreme programming is agile method focused on extremely short delivery cycles and building features at the time when they are actually needed.

You can start your research here: https://www.agilealliance.org/glossary/xp/#q=~(infinite~false~filters~(postType~(~'post~'aa_book~'aa_event_session~'aa_experience_report~'aa_glossary~'aa_research_paper~'aa_video)~tags~(~'xp))~searchTerm~'~sort~false~sortDirection~'asc~page~1)

Contribution guide: https://github.com/DXHeroes/knowledge-base-content/blob/master/CONTRIBUTING.md
