### ISSUE TITLE
Article: Handover

### ISSUE THREAD

**Issue by prokopsimek** [DXHeroes/knowledge-base-content#118]

**Comment by ridlees** [comment]
What is this about: Handover to another team can look as scary. However, with help of certain practices any team can do a great job during Handover phase. 
Read more here: https://www.exponentiallydigital.com/agile-handover/, https://www.researchgate.net/publication/256293238_Is_there_an_Agile_Handover_An_Empirical_Study_of_Documentation_and_Project_Handover_Practices_Across_Agile_Software_Teams, https://kingsinsight.com/2011/02/10/agile-documentation-handover-to-production-support/, https://martinfowler.com/bliki/AgileHandover.html
-  Follow our [Contribution guide](https://github.com/DXHeroes/knowledge-base-content/blob/master/CONTRIBUTING.md)
- How to [Git and Pull Requests]( https://github.com/firstcontributions/first-contributions/blob/master/README.md)
- How to [Markdown](https://guides.github.com/features/mastering-markdown/), [Markdown interactive demo](https://www.markdowntutorial.com/lesson/1/) or [Google Docs Addon](https://gsuite.google.com/marketplace/app/docs_to_markdown/700168918607)

**Comment by schezfaz** [comment]
Hey! can I work on this issue?

**Comment by ridlees** [comment]
@schezfaz Hello, sure, go for it! If you need any help, let me know.

**Comment by DominikMilaniak** [comment]
**Hi again** @schezfaz! 🙂 

A few days have passed since our last contact, how is it going so far with the article? Is anything not clear enough or do you need help with something? I am in no way pushing you, you can take as much time as you need 🙂  Just wanted to get in touch to make sure everything is ok 👍

**Comment by schezfaz** [comment]
Hi @DominikMilaniak! Apologies for being MIA. It's going good so far, will send in a PR soon!! Thanks for checking in. Again, apologies for the delay.

**Comment by DominikMilaniak** [comment]
Hi again @schezfaz!

Please, don't apologize for the delay - there is no time limit and you can take as much time as you need to 🙂  Looking forward to your article! ❤️ 

Have a wonderful day,
Dom

**Comment by schezfaz** [comment]
Hey @DominikMilaniak! I have opened a PR for the same. Let me know what you think! Thanks :D

**Comment by schezfaz** [comment]
Hey @DominikMilaniak, is the article alright?

**Comment by schezfaz** [comment]
Hey @ridlees, please let me know what you think!

**Comment by prokopsimek** [comment]
Hi there, @schezfaz! I am just informing you that we have released a **new feature** to the [DX Knowledge base](https://developerexperience.io), **the author box**.

You are the author of at least one article in the knowledge base, so I am writing to you about it and offering you the opportunity to **add your bio and links under the article**.

![image](https://user-images.githubusercontent.com/5487217/142176190-7e3393c4-9104-4c12-8fe1-9b09c91b8dc7.png)

As you can see, the author box is located at the bottom of the [Apache Kafka page](https://developerexperience.io/practices/kafka).

**If you want to add information about yourself below the article, you must:** 
1. log in to the DX Knowledge Base 
    a. via Github or, 
    b. link your Github account to your Google account on your profile page (https://developerexperience.io/u/me),
2. and fill out the information about yourself in your profile.

If you associate your Github account, an author box will appear in the article.

Thank you and we look forward to placing your box in the article!
