### ISSUE TITLE
Article: Icebreaker

### ISSUE THREAD

**Issue by prokopsimek** [DXHeroes/knowledge-base-content#119]

**Comment by ridlees** [comment]
What is this about: Icebreaker is an activity that helps with getting through the first difficulties in starting a conversation or discussion. 
Read more here: https://www.signupgenius.com/groups/group-icebreakers.cfm, https://www.tinypulse.com/blog/sk-work-icebreaker-games, https://www.eventmanagerblog.com/ice-breakers
-  Follow our [Contribution guide](https://github.com/DXHeroes/knowledge-base-content/blob/master/CONTRIBUTING.md)
- How to [Git and Pull Requests]( https://github.com/firstcontributions/first-contributions/blob/master/README.md)
- How to [Markdown](https://guides.github.com/features/mastering-markdown/), [Markdown interactive demo](https://www.markdowntutorial.com/lesson/1/) or [Google Docs Addon](https://gsuite.google.com/marketplace/app/docs_to_markdown/700168918607)

**Comment by liliancavalet** [comment]
Hello, I would like to work in this issue. Can you please assign me?

**Comment by ridlees** [comment]
Hello @liliancavalet, of course, go for it. I have assigned you to this issue 😄

**Comment by DominikMilaniak** [comment]
**Hi again** @liliancavalet! 🙂 

A few days have passed since our last contact, how is it going so far with the article? Is anything not clear enough or do you need help with something? I am in no way pushing you, you can take as much time as you need 🙂  Just wanted to get in touch to make sure everything is ok 👍

**Comment by liliancavalet** [comment]
Hello, @DominikMilaniak 

Sorry for the really late response, and thanks for reaching out.
Regarding the article is everything is fine, no doubts until now, and I am on my way to finish it.
I hope I can deliver it until this Saturday (Brazilian time).

Regards,
Lilian

**Comment by DominikMilaniak** [comment]
Hi again @liliancavalet!

Don't apologize for the delay, there is was no time limit 🙂  I see you already submitted the PR before I could get back to you, awesome work! ❤️  One of my awesome colleagues, who has experience with tech writing will get back to you asap with feedback. 

Have a wonderful day! 
Dom

**Comment by prokopsimek** [comment]
Hi there, @liliancavalet! I am just informing you that we have released a **new feature** to the [DX Knowledge base](https://developerexperience.io), **the author box**.

You are the author of at least one article in the knowledge base, so I am writing to you about it and offering you the opportunity to **add your bio and links under the article**.

![image](https://user-images.githubusercontent.com/5487217/142176190-7e3393c4-9104-4c12-8fe1-9b09c91b8dc7.png)

As you can see, the author box is located at the bottom of the [Apache Kafka page](https://developerexperience.io/practices/kafka).

**If you want to add information about yourself below the article, you must:** 
1. log in to the DX Knowledge Base 
    a. via Github or, 
    b. link your Github account to your Google account on your profile page (https://developerexperience.io/u/me),
2. and fill out the information about yourself in your profile.

If you associate your Github account, an author box will appear in the article.

Thank you and we look forward to placing your box in the article!
