### ISSUE TITLE
Article: Integration testing

### ISSUE THREAD

**Issue by prokopsimek** [DXHeroes/knowledge-base-content#120]

**Comment by ridlees** [comment]
What is this about: Integration testing is a level of software testing where individual units/components are combined and tested as a group. The purpose of this level of testing is to expose faults in the interaction between integrated units.
Read more here: https://softwaretestingfundamentals.com/integration-testing/, https://www.guru99.com/integration-testing.html, https://www.softwaretestinghelp.com/what-is-integration-testing/
-  Follow our [Contribution guide](https://github.com/DXHeroes/knowledge-base-content/blob/master/CONTRIBUTING.md)
- How to [Git and Pull Requests]( https://github.com/firstcontributions/first-contributions/blob/master/README.md)
- How to [Markdown](https://guides.github.com/features/mastering-markdown/), [Markdown interactive demo](https://www.markdowntutorial.com/lesson/1/) or [Google Docs Addon](https://gsuite.google.com/marketplace/app/docs_to_markdown/700168918607)
