### ISSUE TITLE
Article: Low bus factor

### ISSUE THREAD

**Issue by prokopsimek** [DXHeroes/knowledge-base-content#130]

**Comment by ridlees** [comment]
What is this about: Low Bus factor can hold your team down. However, using certain practices you can improve knowledge and information sharing within your team and increase your Bus factor. 
Read more here: https://dev.to/scottharrisondev/how-to-increase-your-bus-factor-3dpg, https://medium.com/management-matters/whats-the-bus-factor-of-your-team-and-how-to-increase-it-8bdfb63361fc, https://www.5whys.com/articles/team-bus-factors-how-to-reduce-them-and-how-to-prevent-them.html, https://blog.servermania.com/dont-let-a-low-bus-factor-scupper-your-startup/. 
-  Follow our [Contribution guide](https://github.com/DXHeroes/knowledge-base-content/blob/master/CONTRIBUTING.md)
- How to [Git and Pull Requests]( https://github.com/firstcontributions/first-contributions/blob/master/README.md)
- How to [Markdown](https://guides.github.com/features/mastering-markdown/), [Markdown interactive demo](https://www.markdowntutorial.com/lesson/1/) or [Google Docs Addon](https://gsuite.google.com/marketplace/app/docs_to_markdown/700168918607)
