### ISSUE TITLE
Article: Portability

### ISSUE THREAD

**Issue by prokopsimek** [DXHeroes/knowledge-base-content#141]

**Comment by ridlees** [comment]
What is this about: Portability is the ability to be easily carried or moved. The portable product can be run on multiple machines and has architecture around it that supports it.
Read more here: https://en.wikipedia.org/wiki/Portability, https://en.wikipedia.org/wiki/Software_portability, https://www.pcmag.com/encyclopedia/term/software-portability, https://link.springer.com/content/pdf/10.1007%2F1-4020-8159-6_3.pdf.
-  Follow our [Contribution guide](https://github.com/DXHeroes/knowledge-base-content/blob/master/CONTRIBUTING.md)
- How to [Git and Pull Requests]( https://github.com/firstcontributions/first-contributions/blob/master/README.md)
- How to [Markdown](https://guides.github.com/features/mastering-markdown/), [Markdown interactive demo](https://www.markdowntutorial.com/lesson/1/) or [Google Docs Addon](https://gsuite.google.com/marketplace/app/docs_to_markdown/700168918607)
