### ISSUE TITLE
Article: Release Management

### ISSUE THREAD

**Issue by prokopsimek** [DXHeroes/knowledge-base-content#143]

**Comment by ridlees** [comment]
What is this about: Release management is the process of managing, planning, scheduling, and controlling a software build through different stages and environments; including testing and deploying software releases.
Read more here: https://en.wikipedia.org/wiki/Release_management, https://www.lucidchart.com/blog/release-management-process, https://www.microfocus.com/en-us/what-is/release-management
-  Follow our [Contribution guide](https://github.com/DXHeroes/knowledge-base-content/blob/master/CONTRIBUTING.md)
- How to [Git and Pull Requests]( https://github.com/firstcontributions/first-contributions/blob/master/README.md)
- How to [Markdown](https://guides.github.com/features/mastering-markdown/), [Markdown interactive demo](https://www.markdowntutorial.com/lesson/1/) or [Google Docs Addon](https://gsuite.google.com/marketplace/app/docs_to_markdown/700168918607)

**Comment by VinulaUthsara** [comment]
Hi, can I take this up?

**Comment by DominikMilaniak** [comment]
Hello @VinulaUthsara!

I am so excited you want to contribute to our Knowledge Base 🎉 . I see you want to claim 2 more articles - Business model canvas & Continuos delivery. I am therefore assigning you to all 3 articles 🙂 

Looking forward to your articles! ❤️ 
If you need help with anything, don't hesitate to get in touch - I am happy to help 🙂

**Comment by VinulaUthsara** [comment]
@DominikMilaniak Thank you very much, will get to it.

**Comment by VinulaUthsara** [comment]
Hi,

May I please know the method I can use to run this repository locally (or
any other way) to preview changes before creating a Pull Request?

Thankyou in advance,
Vinula Uthsara.

**Comment by VinulaUthsara** [comment]
Hi @DominikMilaniak, please be kind enough to review this PR.

**Comment by prokopsimek** [comment]
Hi there, @VinulaUthsara! I am just informing you that we have released a **new feature** to the [DX Knowledge base](https://developerexperience.io), **the author box**.

You are the author of at least one article in the knowledge base, so I am writing to you about it and offering you the opportunity to **add your bio and links under the article**.

![image](https://user-images.githubusercontent.com/5487217/142176190-7e3393c4-9104-4c12-8fe1-9b09c91b8dc7.png)

As you can see, the author box is located at the bottom of the [Apache Kafka page](https://developerexperience.io/practices/kafka).

**If you want to add information about yourself below the article, you must:** 
1. log in to the DX Knowledge Base 
    a. via Github or, 
    b. link your Github account to your Google account on your profile page (https://developerexperience.io/u/me),
2. and fill out the information about yourself in your profile.

If you associate your Github account, an author box will appear in the article.

Thank you and we look forward to placing your box in the article!
