### ISSUE TITLE
Article: Risk analysis

### ISSUE THREAD

**Issue by prokopsimek** [DXHeroes/knowledge-base-content#146]

**Comment by ridlees** [comment]
What is this about: Is the process of identifying and analyzing potential issues that could negatively impact key business initiatives or projects. This process is done in order to help organizations avoid or mitigate those risks.
Read more here: https://searchsecurity.techtarget.com/definition/risk-analysis, https://www.mindtools.com/pages/article/newTMC_07.htm, https://www.pmi.org/learning/library/risk-analysis-project-management-7070
-  Follow our [Contribution guide](https://github.com/DXHeroes/knowledge-base-content/blob/master/CONTRIBUTING.md)
- How to [Git and Pull Requests]( https://github.com/firstcontributions/first-contributions/blob/master/README.md)
- How to [Markdown](https://guides.github.com/features/mastering-markdown/), [Markdown interactive demo](https://www.markdowntutorial.com/lesson/1/) or [Google Docs Addon](https://gsuite.google.com/marketplace/app/docs_to_markdown/700168918607)

**Comment by ng29** [comment]
Heya, 
@ridlees What's this about? What are the expectations ? I'll love to contribute an article if that's what this is!

Cheers,

**Comment by ridlees** [comment]
Hello @ng29, it is indeed an article. The "What is this about:" part of my previous comment shows you a rough idea of the topic. Moreover, I have added some sources for you (don't feel obligated to use them).

 Thanks a million, I am assigning you. If you had any questions, let me know.

**Comment by ng29** [comment]
Hey @ridlees  / @prokopsimek  

Apologies for the delay(was stuck with shifting), will cook this up tomorrow

Cheers

**Comment by DominikMilaniak** [comment]
Hey @ng29! 🙂 

Please, don't apologize - there is no time limit, you can take as much time as you need. 

I've noticed you want to work on 11 other articles. Even though I think it is absolutely awesome you want to contribute that much to our Knowledge Base, I am little bit afraid if 11 isn't too much. I propose this - I will assign you 2 more articles on top of this one (you can choose which one, just please write me the names or send the issues themselves to this thread). As soon as you would finish all 3 articles, I will gladly assign you another, if you will still feel like it 🙂 

Have a wonderful day,
Dom

**Comment by ng29** [comment]
hey @DominikMilaniak 

Thankss alot for understanding, sure sure will start these first.

https://github.com/DXHeroes/knowledge-base-content/issues/165
https://github.com/DXHeroes/knowledge-base-content/issues/129

Cheers,

**Comment by DominikMilaniak** [comment]
Awesome! I'm assigning you 🙂 

Enjoy your monday (at least in the UTC timezone 😄),
Dom

**Comment by ng29** [comment]
Gracias Dom 💯

**Comment by ng29** [comment]
Hey @DominikMilaniak 
Have baked this dish, rest are in the oven 👍 
Please have a look and review.

**Comment by ng29** [comment]
> Hey @DominikMilaniak
> Have baked this dish, rest are in the oven 👍
> Please have a look and review.

Voila, all done @DominikMilaniak , kindly review them so that i can pick new ones 👍 

Cheers

**Comment by ng29** [comment]
Hey @DominikMilaniak 

Here are more links of articles that i can pick up, please assign it to me.

https://github.com/DXHeroes/knowledge-base-content/issues/122
https://github.com/DXHeroes/knowledge-base-content/issues/125
https://github.com/DXHeroes/knowledge-base-content/issues/126
https://github.com/DXHeroes/knowledge-base-content/issues/127
https://github.com/DXHeroes/knowledge-base-content/issues/153
https://github.com/DXHeroes/knowledge-base-content/issues/167


Cant wait to get more assigned 🔢 

Cheers

**Comment by DominikMilaniak** [comment]
Hi again @ng29!

Amazing work! My colleague will surely review your article as soon as possible ❤️ I will assign you the first 2 issues you've mentioned in your previous message. As soon as these 2 will be finished as well, I will gladly assign you another one or two 🙂 

Have a great day.
Dom

**Comment by prokopsimek** [comment]
Hi there, @ng29! I am just informing you that we have released a **new feature** to the [DX Knowledge base](https://developerexperience.io), **the author box**.

You are the author of at least one article in the knowledge base, so I am writing to you about it and offering you the opportunity to **add your bio and links under the article**.

![image](https://user-images.githubusercontent.com/5487217/142176190-7e3393c4-9104-4c12-8fe1-9b09c91b8dc7.png)

As you can see, the author box is located at the bottom of the [Apache Kafka page](https://developerexperience.io/practices/kafka).

**If you want to add information about yourself below the article, you must:** 
1. log in to the DX Knowledge Base 
    a. via Github or, 
    b. link your Github account to your Google account on your profile page (https://developerexperience.io/u/me),
2. and fill out the information about yourself in your profile.

If you associate your Github account, an author box will appear in the article.

Thank you and we look forward to placing your box in the article!
