### ISSUE TITLE
Article: Sunk Cost

### ISSUE THREAD

**Issue by prokopsimek** [DXHeroes/knowledge-base-content#149]

**Comment by ridlees** [comment]
What is this about : In economics and business decision-making, a sunk cost is a cost that has already been incurred and cannot be recovered. Sunk costs are contrasted with prospective costs, which are future costs that may be avoided if action is taken.
Read more here: https://en.wikipedia.org/wiki/Sunk_cost, https://www.britannica.com/topic/sunk-cost
Contribution guide: https://github.com/DXHeroes/knowledge-base-content/blob/master/CONTRIBUTING.md
