### ISSUE TITLE
Article: Team Culture

### ISSUE THREAD

**Issue by prokopsimek** [DXHeroes/knowledge-base-content#150]

**Comment by ridlees** [comment]
What is this about : Team culture is made up of the values, beliefs, attitudes, and behaviors shared by a team. For some, team culture is what creates a team from people working together.
Read more here: https://tallyfy.com/build-great-team-culture/, https://www.teambuildersplus.com/defining-your-teams-culture/, 
Contribution guide: https://github.com/DXHeroes/knowledge-base-content/blob/master/CONTRIBUTING.md

**Comment by mohitshende** [comment]
I would like to work on this.

**Comment by DominikMilaniak** [comment]
Hi @mohitshende! Thank you for choosing our projects for your contribution! Your wish is my command - I am assigning you to this issue 😄 We are looking forward to your article!

**Comment by mohitshende** [comment]
Thanks @DominikMilaniak .

**Comment by DominikMilaniak** [comment]
**Hi again** @mohitshende! 🙂 

A few days have passed since our last contact, how is it going so far with the article? Is anything not clear enough or do you need help with something? I am in no way pushing you, you can take as much time as you need 🙂  Just wanted to get in touch to make sure everything is ok 👍

**Comment by mohitshende** [comment]
Yeah , everything is fine. Thanks @DominikMilaniak for the concern. I am currently working on it. Its my first time writing this type of article so I'm taking a bit more time. By the way , everyone at DXHeroes is very humble , kind and helpful. Thanks again.

**Comment by DominikMilaniak** [comment]
Happy to hear that @mohitshende 🙂  I am thrilled to hear, that you are stepping out of your comfort zone to contribute to open source ❤️  Take as much time as you need to. Everyone at DX Heroes is looking forward to your article! 

_Btw - you made our day with the last sentence, thank you_ 🙂

**Comment by prokopsimek** [comment]
Hi there, @mohitshende! I am just informing you that we have released a **new feature** to the [DX Knowledge base](https://developerexperience.io), **the author box**.

You are the author of at least one article in the knowledge base, so I am writing to you about it and offering you the opportunity to **add your bio and links under the article**.

![image](https://user-images.githubusercontent.com/5487217/142176190-7e3393c4-9104-4c12-8fe1-9b09c91b8dc7.png)

As you can see, the author box is located at the bottom of the [Apache Kafka page](https://developerexperience.io/practices/kafka).

**If you want to add information about yourself below the article, you must:** 
1. log in to the DX Knowledge Base 
    a. via Github or, 
    b. link your Github account to your Google account on your profile page (https://developerexperience.io/u/me),
2. and fill out the information about yourself in your profile.

If you associate your Github account, an author box will appear in the article.

Thank you and we look forward to placing your box in the article!
