### ISSUE TITLE
Article: Test cards

### ISSUE THREAD

**Issue by prokopsimek** [DXHeroes/knowledge-base-content#154]

**Comment by ridlees** [comment]
What is this about: The Lean ideas stand on customer testing/validating. Test cards are made to help you by asking 4 important questions: The belief, how will you test it, what will you measure and what will you do if you are right.
Read more here: https://www.strategyzer.com/blog/posts/2015/3/5/validate-your-ideas-with-the-test-card
-  Follow our [Contribution guide](https://github.com/DXHeroes/knowledge-base-content/blob/master/CONTRIBUTING.md)
- How to [Git and Pull Requests]( https://github.com/firstcontributions/first-contributions/blob/master/README.md)
- How to [Markdown](https://guides.github.com/features/mastering-markdown/), [Markdown interactive demo](https://www.markdowntutorial.com/lesson/1/) or [Google Docs Addon](https://gsuite.google.com/marketplace/app/docs_to_markdown/700168918607)

**Comment by fanatiicx** [comment]
Hello, I would like to try working on this. I have read the contributing guideline and will refer to the example article for the structure :)

**Comment by prokopsimek** [comment]
@fanatiicx Hi! You're awesome! 👏👍

**Comment by prokopsimek** [comment]
Hi there, @fanatiicx! I am just informing you that we have released a **new feature** to the [DX Knowledge base](https://developerexperience.io), **the author box**.

You are the author of at least one article in the knowledge base, so I am writing to you about it and offering you the opportunity to **add your bio and links under the article**.

![image](https://user-images.githubusercontent.com/5487217/142176190-7e3393c4-9104-4c12-8fe1-9b09c91b8dc7.png)

As you can see, the author box is located at the bottom of the [Apache Kafka page](https://developerexperience.io/practices/kafka).

**If you want to add information about yourself below the article, you must:** 
1. log in to the DX Knowledge Base 
    a. via Github or, 
    b. link your Github account to your Google account on your profile page (https://developerexperience.io/u/me),
2. and fill out the information about yourself in your profile.

If you associate your Github account, an author box will appear in the article.

Thank you and we look forward to placing your box in the article!
