### ISSUE TITLE
Article: Unhappy clients

### ISSUE THREAD

**Issue by prokopsimek** [DXHeroes/knowledge-base-content#155]

**Comment by ridlees** [comment]
What is this about: Unhappy clients are a sign of bad communication, bad information exchange, or delivering "bad" products. This unhappiness hurts your development in the long run cause it can lead to losing a client. Remember, you are never loosing just one client.
Read more here:https://www.creativeboom.com/tips/how-to-deal-with-an-unhappy-client/ 
Contribution guide: https://github.com/DXHeroes/knowledge-base-content/blob/master/CONTRIBUTING.md

**Comment by jmannina** [comment]
Hi, Do these need to be assigned? If so I would like to work on this.

**Comment by ShyamPraveenSingh** [comment]
Hi, I would like to work on this issue.
Can you please assign it to me?

**Comment by ridlees** [comment]
Hello @ShyamPraveenSingh, I have just assigned you on [Responsibility](https://github.com/DXHeroes/knowledge-base-content/issues/1454). If you want, it is no problem for me to assign you to this issue as well. I just want to be sure you are not overwhelmed by work.

**Comment by ShyamPraveenSingh** [comment]
Yes sure, no problem Sir. 
Let me first complete the other issue first and the maybe you can assign me this.

**Comment by ridlees** [comment]
@ShyamPraveenSingh Sure! I will count you as "shadow assigned" (if someone else would like to work on this, we will ask you if you want to give the issue away) 😄

**Comment by ShyamPraveenSingh** [comment]
That is a great idea!

**Comment by ShyamPraveenSingh** [comment]
Hi @prokopsimek, I have made a pull request for the article on Responsibility.
So, can you please review that PR and also now since I am free you can assign me this issue too.
