### ISSUE TITLE
Article: Docker Compose

### ISSUE THREAD

**Issue by prokopsimek** [DXHeroes/knowledge-base-content#163]

**Comment by ridlees** [comment]
What is this about: Compose is a tool for defining and running multi-container Docker applications. With Compose, you use a YAML file to configure your application's services. 
Read more here: https://docs.docker.com/compose/
Contribution guide: https://github.com/DXHeroes/knowledge-base-content/blob/master/CONTRIBUTING.md

**Comment by elaynelemos** [comment]
It would be awesome for me to contribute on it. May I?

**Comment by prokopsimek** [comment]
@elaynelemos Hi, of course, you can!

**Comment by DominikMilaniak** [comment]
**Hi again** @elaynelemos! 🙂 

A few days have passed since our last contact, how is it going so far with the article? Is anything not clear enough or do you need help with something? I am in no way pushing you, you can take as much time as you need 🙂  Just wanted to get in touch to make sure everything is ok 👍

**Comment by elaynelemos** [comment]
> **Hi again** @elaynelemos! 
> 
> A few days have passed since our last contact, how is it going so far with the article? Is anything not clear enough or do you need help with something? I am in no way pushing you, you can take as much time as you need  Just wanted to get in touch to make sure everything is ok

Hey, @DominikMilaniak ! I got a little busy but I didn't forget  the article. For now I don't have any doubts, thanks for your support. I hope I can submit it this week.

**Comment by DominikMilaniak** [comment]
Of course @elaynelemos, take as much time as you need to 🙂  Looking forward to the article!

**Comment by CodeLeom** [comment]
@prokopsimek please assign this to me

**Comment by prokopsimek** [comment]
@CodeLeom Done. Thank you!
