### ISSUE TITLE
Article: Finger pointing & blaming

### ISSUE THREAD

**Issue by prokopsimek** [DXHeroes/knowledge-base-content#170]

**Comment by ridlees** [comment]
What is this about: Finger-pointing and blaming are toxic aspects of work culture. A good team with good leadership avoids this unhealthly habit to ensure their productivity and happiness. Also, it is not part of good developer experience.
Read more here: https://www.workfront.com/blog/stop-the-finger-pointing-how-to-avoid-blame-culture-on-your-project-team
Contribution guide: https://github.com/DXHeroes/knowledge-base-content/blob/master/CONTRIBUTING.md

**Comment by shashwat28nov** [comment]
Hi, can I work on this?
