### ISSUE TITLE
Introduce clean files policy before deployment

### ISSUE THREAD

**Issue by SpiReCZ** [DXHeroes/knowledge-base-content#180]
I noticed that there are some old files on the page: https://preview.developerexperience.io
but not on: https://developerexperience.io

---

Possibly on deployment the existing files are rewritten by the new ones.

The problem is that the old files that are not in git anymore stay at it's place and are not cleaned up properly.

Examples from https://preview.developerexperience.io :

/practices/continous_integration.md (Last updated 4.6.2019) - old leftover
/practices/continuous_integration.md (Last updated 19.7.2019) - new

/practices/unit_tests.md (Last updated 17.5.2019) - old leftover
/practices/unit_testing.md (Last updated 19.7.2019) - new

/practices/penetration_tests.md (Last updated 13.5.2019) - old leftover
/practices/penetration_testing.md (Last updated 25.6.2019) - new

**Comment by prokopsimek** [comment]
@SpiReCZ Thanks for the catch! The behavior is different in production (developerexperience.io) and preview (preview.developerexperience.io) environment. 
Articles in Pull Requests or in `dev` branch are deployed to preview environment. To production are deployed articles in `master` branch only. 
It's for PR review purposes - you can check the article from Pull Request in "preview" environment before merging a PR to `master` branch. 

I agree with you it's weird. Maybe we should "reset" the whole environment at least once in a month? The second solution could be to check all opened PRs and do not delete articles waiting to merge.
