### ISSUE TITLE
Article: Git

### ISSUE THREAD

**Issue by prokopsimek** [DXHeroes/knowledge-base-content#184]
Proposal to add a new article about Git.

Including sources "Understanding Git":
* [Understanding Git — Data Model](https://hackernoon.com/https-medium-com-zspajich-understanding-git-data-model-95eb16cc99f5)
* [Understanding Git — Branching](https://hackernoon.com/understanding-git-branching-2662f5882f9)
* [Understanding Git — Index](https://hackernoon.com/understanding-git-index-4821a0765cf)

**Comment by ridlees** [comment]
Just adding Contribution guide: https://github.com/DXHeroes/knowledge-base-content/blob/master/CONTRIBUTING.md

**Comment by ramesht007** [comment]
hey @prokopsimek , can I work on this

**Comment by ridlees** [comment]
Hello, sure, go for it!

**Comment by ramesht007** [comment]
Hi, @ridlees the above links for Git- data model,Branching, and index are not working. can you please share any other link.
Thanks

**Comment by prokopsimek** [comment]
@ramesht007 There are these same articles on Medium. 📝

https://medium.com/hackernoon/https-medium-com-zspajich-understanding-git-data-model-95eb16cc99f5
https://medium.com/hackernoon/understanding-git-branching-2662f5882f9
https://medium.com/hackernoon/understanding-git-index-4821a0765cf

**Comment by ramesht007** [comment]
Thanks @prokopsimek , I will look into it

**Comment by hritikkhurana10sm** [comment]
Can u work on this issue . please

**Comment by hritikkhurana10sm** [comment]
Can I work on this issue . Please

**Comment by ridlees** [comment]
Hello @hritikkhurana10sm, @ramesht007 is currently working on this issue and has opened a PR that solves it. Would you mind looking at the rest of our issues https://github.com/DXHeroes/knowledge-base-content/issues and pick one that is open?

**Comment by prokopsimek** [comment]
Hi there, @ramesht007! I am just informing you that we have released a **new feature** to the [DX Knowledge base](https://developerexperience.io), **the author box**.

You are the author of at least one article in the knowledge base, so I am writing to you about it and offering you the opportunity to **add your bio and links under the article**.

![image](https://user-images.githubusercontent.com/5487217/142176190-7e3393c4-9104-4c12-8fe1-9b09c91b8dc7.png)

As you can see, the author box is located at the bottom of the [Apache Kafka page](https://developerexperience.io/practices/kafka).

**If you want to add information about yourself below the article, you must:** 
1. log in to the DX Knowledge Base 
    a. via Github or, 
    b. link your Github account to your Google account on your profile page (https://developerexperience.io/u/me),
2. and fill out the information about yourself in your profile.

If you associate your Github account, an author box will appear in the article.

Thank you and we look forward to placing your box in the article!
