### ISSUE TITLE
Article: Cookie Consent

### ISSUE THREAD

**Issue by ridlees** [DXHeroes/knowledge-base-content#260]
What is this about: Why Do you create the consent screen? How do consents differ between UK/EU/US? Ex. In the UK, you need "active" consent.
Read more: https://www.smashingmagazine.com/2019/04/privacy-ux-better-cookie-consent-experiences/, https://www.privacypolicies.com/blog/cookie-consent-examples/, https://matomo.org/cookie-consent-banners/, https://consent.yahoo.com/v2/collectConsent?sessionId=3_cc-session_911c6c53-87d3-4aee-a4a5-d336612096d9
-  Follow our [Contribution guide](https://github.com/DXHeroes/knowledge-base-content/blob/master/CONTRIBUTING.md)
- How to [Git and Pull Requests]( https://github.com/firstcontributions/first-contributions/blob/master/README.md)
- How to [Markdown](https://guides.github.com/features/mastering-markdown/), [Markdown interactive demo](https://www.markdowntutorial.com/lesson/1/) or [Google Docs Addon](https://gsuite.google.com/marketplace/app/docs_to_markdown/700168918607)

**Comment by hacky1997** [comment]
@ridlees I want to work on this. Could you please assign me to this?

**Comment by prokopsimek** [comment]
@hacky1997 Hi! Sure. Go for it!

Do not forget to follow our [Contribution guide](https://github.com/DXHeroes/knowledge-base-content/blob/master/CONTRIBUTING.md).

**Comment by DominikMilaniak** [comment]
**Hi again** @hacky1997! 🙂 

A few days have passed since our last contact, how is it going so far with the article? Is anything not clear enough or do you need help with something? I am in no way pushing you, you can take as much time as you need 🙂  Just wanted to get in touch to make sure everything is ok 👍

**Comment by hacky1997** [comment]
@DominikMilaniak Extremely sorry. Actually, I am a bit busy with the company's task. So, that's why it is not completed yet. But I will surely do this within a short time period. Thank you so much. :)

**Comment by DominikMilaniak** [comment]
Don't apologize @hacky1997 - take as much time as you need to. I 100% understand, that the company task is way more important. I just wanted to know if everything is ok and clear 🙂  Looking forward to your PR! ❤️

**Comment by hacky1997** [comment]
@DominikMilaniak Sorry I totally forgot about this PR. I will make a pull request today at night
