### ISSUE TITLE
New article: Refactoring

### ISSUE THREAD

**Issue by zeman-j4** [DXHeroes/knowledge-base-content#261]
New article: Refactoring

What is this about: Software needs to be made sleeker, faster, better looking. For this, you have to refactor code - change the inner workings without changing the functionality. Elaborate on the right procedures and rules to follow.

Read more here: https://refactoring.com/

## How to contribute:
- Follow our [Contribution guide](https://github.com/DXHeroes/knowledge-base-content/blob/master/CONTRIBUTING.md)
- How to [Git and Pull Requests]( https://github.com/firstcontributions/first-contributions/blob/master/README.md)
- How to [Markdown](https://guides.github.com/features/mastering-markdown/), [Markdown interactive demo](https://www.markdowntutorial.com/lesson/1/) or [Google Docs Addon](https://gsuite.google.com/marketplace/app/docs_to_markdown/700168918607)

**Comment by shashwat28nov** [comment]
Hello, can I work on this?

**Comment by K-Kumar-01** [comment]
Hello @zeman-j4  can i have a go at this issue?

**Comment by DominikMilaniak** [comment]
Hi @shashwat28nov and @K-Kumar-01!

First of all, I would like to apologize to you, @shashwat28nov. Your message completely flew under my radar and I apologize for answering this late 😞 If you still want to work on this article, I will assign it to you right away. If not, I will gladly assign this article to you @K-Kumar-01 🙂 

Have a wonderful day,
Dominic

**Comment by K-Kumar-01** [comment]
@DominikMilaniak 
As there is no reply from @shashwat28nov, can i have the issue?

**Comment by DominikMilaniak** [comment]
Hi again @K-Kumar-01.

Yes, I see. All right - I am assigning this article to you 🙂 Have fun!

**Comment by K-Kumar-01** [comment]
@DominikMilaniak  
I made a PR for the article. Please let me know if any fixes are required.

**Comment by K-Kumar-01** [comment]
@DominikMilaniak 
Any updates on my PR?

**Comment by K-Kumar-01** [comment]
@DominikMilaniak 
Any updates on [this](https://github.com/DXHeroes/knowledge-base-content/pull/316)

**Comment by prokopsimek** [comment]
Hi there, @K-Kumar-01! I am just informing you that we have released a **new feature** to the [DX Knowledge base](https://developerexperience.io), **the author box**.

You are the author of at least one article in the knowledge base, so I am writing to you about it and offering you the opportunity to **add your bio and links under the article**.

![image](https://user-images.githubusercontent.com/5487217/142176190-7e3393c4-9104-4c12-8fe1-9b09c91b8dc7.png)

As you can see, the author box is located at the bottom of the [Apache Kafka page](https://developerexperience.io/practices/kafka).

**If you want to add information about yourself below the article, you must:** 
1. log in to the DX Knowledge Base 
    a. via Github or, 
    b. link your Github account to your Google account on your profile page (https://developerexperience.io/u/me),
2. and fill out the information about yourself in your profile.

If you associate your Github account, an author box will appear in the article.

Thank you and we look forward to placing your box in the article!
