### ISSUE TITLE
Update article: Pull Requests

### ISSUE THREAD

**Issue by ridlees** [DXHeroes/knowledge-base-content#266]
- [x] Link to practice: "https://developerexperience.io/practices/pull-requests"

- [x] What is this about: I would like to enrich the "anatomy" of a pull request from the current version: _Encourage small pull requests. Nobody wants to review 5000+ lines of changes within one PR._ according to this article (https://medium.com/@hugooodias/the-anatomy-of-a-perfect-pull-request-567382bb6067)

## How to contribute:
- Follow our [Contribution guide](https://github.com/DXHeroes/knowledge-base-content/blob/master/CONTRIBUTING.md)
- How to [Git and Pull Requests]( https://github.com/firstcontributions/first-contributions/blob/master/README.md)
- How to [Markdown](https://guides.github.com/features/mastering-markdown/), [Markdown interactive demo](https://www.markdowntutorial.com/lesson/1/) or [Google Docs Addon](https://gsuite.google.com/marketplace/app/docs_to_markdown/700168918607)

**Comment by snehal199** [comment]
can I pick this up @ridlees ?

**Comment by ridlees** [comment]
@snehal199 Sure, go for it!

**Comment by snehal199** [comment]
@ridlees I plan to change the point to- "Encourage pull requests that are short and solve a specific problem. Also inculcate the practice of giving pull requests a relevant and precise title and description. These practices make the process of code review and product development faster,easier and more efficient."

Would that be good or should I make some changes?

**Comment by ShyamPraveenSingh** [comment]
Can anyone explain to me what is this issue about?
I would to work on it.

**Comment by ridlees** [comment]
@snehal199 Thanks for the question. I would suggest expanding the part about the anatomy of a great pull request. In the article I have linked, you have some specific details (like that pull request should be smaller than 250 lines of code). I would also recommend adding the article into sources for the Pull request article. Similarly, you could explore the relevant title and description part. There is an example pull request in the medium post. You can find info about character limit or samples inn sources like https://github.blog/2015-01-21-how-to-write-the-perfect-pull-request/ or https://www.atlassian.com/blog/git/written-unwritten-guide-pull-requests.

**Comment by ridlees** [comment]
@ShyamPraveenSingh Hello, this issue is about updating an existing article in our Knowledge Base with the anatomy of a good pull request. @snehal199 is currently working on this. You can look at [other curated issues](https://github.com/DXHeroes/knowledge-base-content/contribute) if you want to contribute.

**Comment by DominikMilaniak** [comment]
**Hi again** @snehal199! 🙂 

A few days have passed since our last contact, how is it going so far with the article? Is anything not clear enough or do you need help with something? I am in no way pushing you, you can take as much time as you need 🙂  Just wanted to get in touch to make sure everything is ok 👍

If you are no longer interested in writing this article - which is completely fine 🙂  I will happily assign this article to someone else, possibly @ShyamPraveenSingh, if he's still interested in creating it 🙂

**Comment by ShyamPraveenSingh** [comment]
Yes Sir @DominikMilaniak very much interested! 😃

**Comment by snehal199** [comment]
Sorry for the delay @DominikMilaniak  :sweat_smile:  , I would be making a pr for the issue soon.

**Comment by ShyamPraveenSingh** [comment]
Yes I totally understand.
Let me browse through the issues list and I'll let you know about it.
