### ISSUE TITLE
Update article: Package management

### ISSUE THREAD

**Issue by ridlees** [DXHeroes/knowledge-base-content#268]
- [x] Link to practice: "https://developerexperience.io/practices/package-management"

- [x] What is this about: "Add Java Specifying dependencies (Maven or Gradle)"

## How to contribute:
- Follow our [Contribution guide](https://github.com/DXHeroes/knowledge-base-content/blob/master/CONTRIBUTING.md)
- How to [Git and Pull Requests]( https://github.com/firstcontributions/first-contributions/blob/master/README.md)
- How to [Markdown](https://guides.github.com/features/mastering-markdown/), [Markdown interactive demo](https://www.markdowntutorial.com/lesson/1/) or [Google Docs Addon](https://gsuite.google.com/marketplace/app/docs_to_markdown/700168918607)

**Comment by wilsantow** [comment]
can I work on this issue @ridlees ?

**Comment by ridlees** [comment]
Hello, @wilsantow, of course!
