### ISSUE TITLE
New article: Infrastructure as a Code

### ISSUE THREAD

**Issue by prokopsimek** [DXHeroes/knowledge-base-content#293]
# Title: Infrastructure as a Code

- [x] What is this about: “What is this practice about”? Which existing (or new) problems does this practice solve? 

The article is about the automation of DevOps processes. How is it possible to automate deployment do cloud services (e.g. Kubernetes), recommended tools, what's the main target of the automation and what benefits it has.

- [x] Read more here: The starting point for your research (You can use different sources if you have better ones)
- https://en.wikipedia.org/wiki/Infrastructure_as_code
- https://stackify.com/what-is-infrastructure-as-code-how-it-works-best-practices-tutorials/
- https://www.ibm.com/cloud/learn/infrastructure-as-code
- https://docs.microsoft.com/en-us/azure/devops/learn/what-is-infrastructure-as-code

- [x] Pick the corresponding labels: 
    - Stage:research
    - Stage:building_team
    - **Stage:development**
    - Stage:launch
    - **Stage:maintenance**
    - Stage:phase_out

## How to contribute:
- Follow our [Contribution guide](https://github.com/DXHeroes/knowledge-base-content/blob/master/CONTRIBUTING.md)
- How to [Git and Pull Requests]( https://github.com/firstcontributions/first-contributions/blob/master/README.md)
- How to [Markdown](https://guides.github.com/features/mastering-markdown/), [Markdown interactive demo](https://www.markdowntutorial.com/lesson/1/) or [Google Docs Addon](https://gsuite.google.com/marketplace/app/docs_to_markdown/700168918607)

**Comment by ng29** [comment]
hey @prokopsimek 
Can i contribute in this ??
