### ISSUE TITLE
New article: Software Development Kit (SDK)

### ISSUE THREAD

**Issue by pamichalik** [DXHeroes/knowledge-base-content#308]
# Title: Software Development Kit (SDK)

- [ ] What is this about: “What is this practice about”? Which existing (or new) problems does this practice solve? 
Description of what SDK is, how it helps developers, and what it should contain. It is also good to mention the differences between SDK and API.

- [ ] Read more here: The starting point for your research (You can use different sources if you have better ones)
https://en.wikipedia.org/wiki/Software_development_kit

- [ ] Pick the corresponding labels: 
    - Stage:research
    - Stage:building_team
    - Stage:development
    - Stage:launch
    - Stage:maintenance
    - Stage:phase_out

## How to contribute:
- Follow our [Contribution guide](https://github.com/DXHeroes/knowledge-base-content/blob/master/CONTRIBUTING.md)
- How to [Git and Pull Requests]( https://github.com/firstcontributions/first-contributions/blob/master/README.md)
- How to [Markdown](https://guides.github.com/features/mastering-markdown/), [Markdown interactive demo](https://www.markdowntutorial.com/lesson/1/) or [Google Docs Addon](https://gsuite.google.com/marketplace/app/docs_to_markdown/700168918607)

**Comment by sudiptog81** [comment]
Can I contribute towards addressing this issue?

**Comment by DominikMilaniak** [comment]
Hi @sudiptog81!

Of course! I am super glad you chose our DX Knowledge Base for your contribution. I am assigning you to this article, have fun 🙂  Looking forward to what you will create!

**Comment by prokopsimek** [comment]
Hi there, @sudiptog81 ! I am just informing you that we have released a **new feature** to the [DX Knowledge base](https://developerexperience.io), **the author box**.

You are the author of at least one article in the knowledge base, so I am writing to you about it and offering you the opportunity to **add your bio and links under the article**.

![image](https://user-images.githubusercontent.com/5487217/142176190-7e3393c4-9104-4c12-8fe1-9b09c91b8dc7.png)

As you can see, the author box is located at the bottom of the [Apache Kafka page](https://developerexperience.io/practices/kafka).

**If you want to add information about yourself below the article, you must:** 
1. log in to the DX Knowledge Base 
    a. via Github or, 
    b. link your Github account to your Google account on your profile page (https://developerexperience.io/u/me),
2. and fill out the information about yourself in your profile.

If you associate your Github account, an author box will appear in the article.

Thank you and we look forward to placing your box in the article!
