### ISSUE TITLE
New article: Respectful Code Reviews

### ISSUE THREAD

**Issue by prokopsimek** [DXHeroes/knowledge-base-content#317]
# Title: Respectful Code Reviews

- [ ] What is this about: “What is this practice about”? Which existing (or new) problems does this practice solve? 
A guide for respectful code reviews.

- [ ] Read more here: The starting point for your research (You can use different sources if you have better ones)
- https://chromium.googlesource.com/chromium/src/+/master/docs/cr_respect.md

- [ ] Pick the corresponding labels: 
    - Stage:research
    - Stage:building_team
    - **Stage:development**
    - Stage:launch
    - Stage:maintenance
    - Stage:phase_out

## How to contribute:
- Follow our [Contribution guide](https://github.com/DXHeroes/knowledge-base-content/blob/master/CONTRIBUTING.md)
- How to [Git and Pull Requests]( https://github.com/firstcontributions/first-contributions/blob/master/README.md)
- How to [Markdown](https://guides.github.com/features/mastering-markdown/), [Markdown interactive demo](https://www.markdowntutorial.com/lesson/1/) or [Google Docs Addon](https://gsuite.google.com/marketplace/app/docs_to_markdown/700168918607)

**Comment by ShvetaVasisht** [comment]
hi,
Please let me know if i can work on this issue.
Thanks
Shveta

**Comment by prokopsimek** [comment]
@ShvetaVasisht Hi, of course you can! Thanks!

**Comment by prokopsimek** [comment]
Done ✅
