### ISSUE TITLE
New article: YAGNI principle

### ISSUE THREAD

**Issue by prokopsimek** [DXHeroes/knowledge-base-content#318]
# Title: YAGNI principle

- [ ] What is this about: “What is this practice about”? Which existing (or new) problems does this practice solve? 
Don’t codify more than you’ve been asked to. Don’t anticipate the future, and just create something that works as soon as possible. Code only the necessary parts to solve the current problem.

- [ ] Read more here: The starting point for your research (You can use different sources if you have better ones)
-https://en.wikipedia.org/wiki/You_aren%27t_gonna_need_it

- [ ] Pick the corresponding labels: 
    - Stage:research
    - Stage:building_team
    - **Stage:development**
    - Stage:launch
    - Stage:maintenance
    - Stage:phase_out

## How to contribute:
- Follow our [Contribution guide](https://github.com/DXHeroes/knowledge-base-content/blob/master/CONTRIBUTING.md)
- How to [Git and Pull Requests]( https://github.com/firstcontributions/first-contributions/blob/master/README.md)
- How to [Markdown](https://guides.github.com/features/mastering-markdown/), [Markdown interactive demo](https://www.markdowntutorial.com/lesson/1/) or [Google Docs Addon](https://gsuite.google.com/marketplace/app/docs_to_markdown/700168918607)

**Comment by ShvetaVasisht** [comment]
Hi,
Can I work on this issue?
Thanks
Shveta

**Comment by prokopsimek** [comment]
@ShvetaVasisht Hi! You're welcome! Please, beware of plagiarism. :) Thanks!

**Comment by ShvetaVasisht** [comment]
Sure :-).
Just 2 quick questions 
1) What is covered_by_dx_scanner: in the template_practice.md
2) I can see some broken Markdown(2 headings) in https://developerexperience.io/practices/respectful-code-review.Should I fix them along with this?
Thanks

**Comment by prokopsimek** [comment]
@ShvetaVasisht Thank you for your questions.

1. the `covered_by_dx_scanner ` is an indicator if the [DX Scanner](https://github.com/DXHeroes/dx-scanner) tool can measure this practice. The value for YAGNI is should be `false` 👍 
2. It would be great! Thank you 👏

**Comment by ShvetaVasisht** [comment]
Created pull request for the issue. Please see.
thanks

**Comment by prokopsimek** [comment]
Hi there, @ShvetaVasisht! I am just informing you that we have released a **new feature** to the [DX Knowledge base](https://developerexperience.io), **the author box**.

You are the author of at least one article in the knowledge base, so I am writing to you about it and offering you the opportunity to **add your bio and links under the article**.

![image](https://user-images.githubusercontent.com/5487217/142176190-7e3393c4-9104-4c12-8fe1-9b09c91b8dc7.png)

As you can see, the author box is located at the bottom of the [Apache Kafka page](https://developerexperience.io/practices/kafka).

**If you want to add information about yourself below the article, you must:** 
1. log in to the DX Knowledge Base 
    a. via Github or, 
    b. link your Github account to your Google account on your profile page (https://developerexperience.io/u/me),
2. and fill out the information about yourself in your profile.

If you associate your Github account, an author box will appear in the article.

Thank you and we look forward to placing your box in the article!
