### ISSUE TITLE
New article: Refactoring

### ISSUE THREAD

**Issue by prokopsimek** [DXHeroes/knowledge-base-content#322]
# Title: Refactoring

- [ ] What is this about: “What is this practice about”? Which existing (or new) problems does this practice solve? 
Refactoring is a disciplined technique for restructuring an existing body of code, altering its internal structure without changing its external behavior.

- [ ] Read more here: The starting point for your research (You can use different sources if you have better ones)
https://refactoring.com

- [ ] Pick the corresponding labels: 
    - Stage:research
    - Stage:building_team
    - **Stage:development**
    - Stage:launch
    - **Stage:maintenance**
    - Stage:phase_out

## How to contribute:
- Follow our [Contribution guide](https://github.com/DXHeroes/knowledge-base-content/blob/master/CONTRIBUTING.md)
- How to [Git and Pull Requests]( https://github.com/firstcontributions/first-contributions/blob/master/README.md)
- How to [Markdown](https://guides.github.com/features/mastering-markdown/), [Markdown interactive demo](https://www.markdowntutorial.com/lesson/1/) or [Google Docs Addon](https://gsuite.google.com/marketplace/app/docs_to_markdown/700168918607)

**Comment by schezfaz** [comment]
Hi hii! I would love to work on this issue. May I take it forward? #hacktoberfest2021

**Comment by prokopsimek** [comment]
@schezfaz HI! Go for it! You're welcome. Please, follow our [Contribution guide](https://github.com/DXHeroes/knowledge-base-content/blob/master/CONTRIBUTING.md). Thanks!

**Comment by CodeLeom** [comment]
Can I get this assigned to me?

**Comment by prokopsimek** [comment]
@CodeLeom

**Comment by CodeLeom** [comment]
@prokopsimek I just checked the practice folder and noticed this article have been written

**Comment by prokopsimek** [comment]
@CodeLeom Sorry for that, I have forgot to mark it as done. Thanks for check!
