### ISSUE TITLE
New article: Vision (company or team or product vision)

### ISSUE THREAD

**Issue by prokopsimek** [DXHeroes/knowledge-base-content#374]
# Title: Vision

- [x] What is this about: “What is this practice about”? Which existing (or new) problems does this practice solve? 

It's about motivating people, product development, and development itself by a company/product/team vision. What's vision and how it drives motivation or team to better alignment with a purpose.

- [x] Read more here: The starting point for your research (You can use different sources if you have better ones)

- https://www.productboard.com/blog/write-product-vision/
- https://examples.yourdictionary.com/best-examples-of-a-vision-statement.html
- https://www.businessnewsdaily.com/3882-vision-statement.html
- https://www.scrum.org/resources/blog/10-tips-product-owners-product-vision

- [x] Pick the corresponding labels: 
    - Stage:research
    - **Stage:building_team**
    - **Stage:development**
    - Stage:launch
    - Stage:maintenance
    - Stage:phase_out

## How to contribute:
- Follow our [Contribution guide](https://github.com/DXHeroes/knowledge-base-content/blob/master/CONTRIBUTING.md)
- How to [Git and Pull Requests]( https://github.com/firstcontributions/first-contributions/blob/master/README.md)
- How to [Markdown](https://guides.github.com/features/mastering-markdown/), [Markdown interactive demo](https://www.markdowntutorial.com/lesson/1/) or [Google Docs Addon](https://gsuite.google.com/marketplace/app/docs_to_markdown/700168918607)

**Comment by fanatiicx** [comment]
@prokopsimek Thanks for the resources, will work on this and the mission article soon!
