### ISSUE TITLE
Broken Image Link in documentation.md

### ISSUE THREAD

**Issue by wilsantow** [DXHeroes/knowledge-base-content#380]
## Expected Behavior
Image under the subheading "What is Documentation" in the page [Documentation](https://developerexperience.io/practices/documentation) must be visible.

## Current Behavior
Image is not visible since the link is broken.
## Possible Solution
1. Changing the relative path of the image from */files/documentation* to */files/documentation.png* fixes the issue.
2. Additionally the original source URL of the image can be updated below this [medium article](https://medium.com/datasheetest-by-tdsmaker/basics-of-technical-documentation-for-engineers-36deab8d1220) to [Pinclipart site](https://www.pinclipart.com/pindetail/JJoJJT_choice-clipart-process-documentation-png-download/).
## Steps to Reproduce

1. Navigate to [Documentation](https://developerexperience.io/practices/documentation).

**Comment by wilsantow** [comment]
Hi @prokopsimek , I authored this particular article in #288 and had missed this one. Let me know if I can make the changes and open a PR.

**Comment by prokopsimek** [comment]
@wilsantow You're welcome! 😉
