### ISSUE TITLE
New article: API Authentication

### ISSUE THREAD

**Issue by prokopsimek** [DXHeroes/knowledge-base-content#393]
# Title: [Article] API Authentication

- [x] What is this about: “What is this practice about”? Which existing (or new) problems does this practice solve? 
How to properly set API credentials. Do not use body because of logging. Do not use username and password - the same issue. Use headers and just API key.

- [x] Read more here: The starting point for your research (You can use different sources if you have better ones)

- [ ] Pick the corresponding labels: 
    - Stage:development

## How to contribute:
- Follow our [Contribution guide](https://github.com/DXHeroes/knowledge-base-content/blob/master/CONTRIBUTING.md)
- How to [Git and Pull Requests]( https://github.com/firstcontributions/first-contributions/blob/master/README.md)
- How to [Markdown](https://guides.github.com/features/mastering-markdown/), [Markdown interactive demo](https://www.markdowntutorial.com/lesson/1/) or [Google Docs Addon](https://gsuite.google.com/marketplace/app/docs_to_markdown/700168918607)

**Comment by CodeLeom** [comment]
Can I get this assigned to me?
