### ISSUE TITLE
API-first design

### ISSUE THREAD

**Issue by D-stevpm** [DXHeroes/knowledge-base-content#400]
# Title: API-First design 

- [ ] What is this about: The goal of this article is to follow up on the previous article API-First Development. Here I will be writing about API specifications, how to design endpoints, and might be writing about YAML which is a human-readable data-serialization language

- [ ] Pick the corresponding labels: 
    - Stage:research

## How to contribute:
- Follow our [Contribution guide](https://github.com/DXHeroes/knowledge-base-content/blob/master/CONTRIBUTING.md)
- How to [Git and Pull Requests]( https://github.com/firstcontributions/first-contributions/blob/master/README.md)
- How to [Markdown](https://guides.github.com/features/mastering-markdown/), [Markdown interactive demo](https://www.markdowntutorial.com/lesson/1/) or [Google Docs Addon](https://gsuite.google.com/marketplace/app/docs_to_markdown/700168918607)

**Comment by prokopsimek** [comment]
Let's do that! Sorry for the delay. I have some issues with GitHub notifications.

**Comment by CodeLeom** [comment]
@prokopsimek this article has been written, this issue can be closed
