### ISSUE TITLE
Article: Absolute ownership

### ISSUE THREAD

**Issue by prokopsimek** [DXHeroes/knowledge-base-content#91]

**Comment by zeman-j4** [comment]
What this is about: Taking absolute ownership in a project or team can be useful and sometimes even necessary. Keep it mind, that it isn't the only way thinks can be done.

You can start your research here: https://simpleprogrammer.com/extreme-ownership-programming-career/

Contribution guide: https://github.com/DXHeroes/knowledge-base-content/blob/master/CONTRIBUTING.md

**Comment by SeaghdhVittMacCailein** [comment]
Hey,

I have written an article on the topic and submitted a pull request.

Thank you!
